name: Build README.md
on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  download-icons:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check.outputs.skip }}
    steps:
      # Ignore normal issue events
      - name: Exit if is not a pool issue
        id: "check"
        if: "${{ github.event_name == 'issues' && github.event.action != 'deleted' && !contains(github.event.issue.labels.*.name, 't: pool') }}"
        run: echo "::set-output name=skip::true"

  build-readme:
    runs-on: ubuntu-latest
    needs: verify-issue
    if: ${{ needs.verify-issue.outputs.skip != 'true' }}
    steps:
      # Clone and setup local repository
      - uses: actions/checkout@v1

      # Setup Java
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "8"

      # Build markdown and update the `README.md`
      - name: Build README.md Job
        env:
          GITHUB_REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
          REPOSITORY: ${{ github.repository }}
        run: cd actions && bash ./gradlew run -P JOB=GenerateMarkdownTable
